CREATE DATABASE IF NOT EXISTS storefront;
CREATE DATABASE IF NOT EXISTS storefront_test;

CREATE USER IF NOT EXISTS admin WITH PASSWORD 'admin';

GRANT ALL PRIVILEGES ON DATABASE storefront TO admin;
GRANT ALL PRIVILEGES ON DATABASE storefront_test TO admin;